// Generated by   : ImageConverter 565 Online
// Generated from : scrollUp.png
// Time generated : Thu, 06 Apr 23 04:29:45 +0200  (Server timezone: CET)
// Image Size     : 5x3 pixels
// Memory usage   : 30 bytes


#if defined(__AVR__)
    #include <avr/pgmspace.h>
#elif defined(__PIC32MX__)
    #define PROGMEM
#elif defined(__arm__)
    #define PROGMEM
#endif

const unsigned short scrollUp[15] PROGMEM={
};
